language: node_js
node_js:
  - node
  - 5
services:
  - mongodb
before_script:
  - mongo events_db --eval 'db.createUser({user:"sarra",pwd:"sarra",roles:["readWrite"]});'
  - mongo events_db --eval 'db.createCollection("events");'
  - sleep 15
test: npm test
